export enum AppErrors {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_INACTIVE = "USER_INACTIVE",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  ROLE_ALREADY_ASSIGNED = "ROLE_ALREADY_ASSIGNED",

  // Generic errors
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
}
